### PR TITLE
Add mid python month report

### PR DESCRIPTION
**Pull request by kracekumar**
@harisibrahimkv @vnbang2003 Please review the content. I will add charts and images later once the content is approved. The PR has all relevant images.

@ChillarAnand Can you advise on attaching the image? Is there a documented way of adding the image in `jinja2` syntax or use `` tag in the source code?

### CODE REVIEW

**Comment by vnbang2003** [comment]
Is that possible to add more photo or link like below.

https://twitter.com/red_suraj/status/772067946021593088
https://cosmologist10.wordpress.com/2016/08/29/python-monthvolunteering-experience-under-python-express/

**Comment by kracekumar** [comment]
@vnbang2003 Sure. Do you want to add it in this post or at the final wrap up post?

**Comment by vnbang2003** [comment]
@kracekumar I think workshop which happened before 30 we can add.
Probably we can add this in the blog: https://cosmologist10.wordpress.com/2016/08/29/python-monthvolunteering-experience-under-python-express/

Should we thanks even coordinator group for back group support ?

**Comment by kracekumar** [comment]
@vnbang2003 Modified. Check the bottom section; included software development team.

**Comment by vnbang2003** [comment]
@kracekumar thanks looks good to me

**Comment by ChillarAnand** [comment]
@kracekumar  `img` in source code should be fine.

**Comment by kracekumar** [comment]
@ChillarAnand But that requires us to host in Dropbox, Imgur, or Google Drive.

**Comment by ChillarAnand** [comment]
We can create an issue here saying images and can upload all images in that issue?

**Comment by ChillarAnand** [comment]
Images should be added in the same folder of the post and you can use them as

```
<img src="foo.png">
```

**Comment by kracekumar** [comment]
@ChillarAnand I'm unable to spot the post. Any help?

**Pull request merged**
